### PR TITLE
Addded major_version input variable…

### PR DESCRIPTION
**Pull request by fuzzylogiq**
… (which defaults to 'latest') so that recipes can be overridden to download specific versions.

We wish to be able to control the major version of VMware Fusion we're downloading with the recipe so I've introduced this with a default so it's backwards compatible with previous users. Also cleaned up some whitespace anomalies a bit because my python linter was complaining :)

### CODE REVIEW

**Comment by justinrummel** [comment]
Nice!

I haven't updated/looked at this .py in a very long time, and I no longer support Mac deployments for a job.

@rtrouton want to put your eyes on this.  I know you used to use this for your VM Deployments.  I've looked at the code and it seems good, just would like a sanity check.

**Comment by fuzzylogiq** [comment]
I wonder if it might be better if you're no longer working in the field and not able to test if we at University of Oxford's Orchard team take over these VMWare Fusion recipes in our repo? I would suggest we fork them, change the identifiers and leave a note in your repo saying where to repo-add the recipes from again (deprecating your ones so they don't appear in autopkg search. What do you think?

**Comment by justinrummel** [comment]
I'm happy to place a note that these items are deprecated.  However, I don't want to remove them from AutoPKG as some people may have dependancies and things may break.

@timsutton @gregneagle thoughts on this.  How do we sunset recipes?

**Comment by gregneagle** [comment]
@justinrummel If you don't plan to maintain these recipes, I think you should simply remove them if they are broken. No-one currently using them is going to know to look for a note in your repo in advance of a planned removal. I think it would be nice to keep the repo itself around for a bit, containing a note about what happened to the recipes.

So: person using your recipes does a repo-update and things break. They visit your repo and see the note. They then make whatever adjustments are needed.

**Comment by justinrummel** [comment]
@gregneagle nothing is broken, just not as feature rich as @fuzzylogiq is requesting.   I'll keep the repo, around since things work and will provide a note once a newer version is available; and also state I will stop supporting any changes going forward so we don't have two forks that may have changes.

**Comment by fuzzylogiq** [comment]
They're not strictly speaking broken, but we'd be happy to take over their maintenance (and make improvements), but we'd want to change the identifiers, which would break existing users overrides/dependencies, leading them to your repo and the note that they'd moved. It would break/confuse autopkg search to have them in both locations

**Comment by justinrummel** [comment]
For what it's worth, I'm happy to do approve PR's, however, I have no method to test.  I don't think anyone would want me to approve any PR that just comes my way.  If @fuzzylogiq can get someone else to review and chime in, I'll complete the Merge request.

**Comment by MLBZ521** [comment]
@justinrummel I have tested this change and it works to pull specific versions.

However, the way the code was written, it is no longer functioning 'properly' to get the most recently release with `latest`.

Specifically, `latest` pulls the most recent version of Fusion 8.x.x.  While Fusion 10.x.x is now available.

Unfortunately, I'm not familiar enough with Python yet to propose a resolution at this time.  But setting the value to any major version (ex. 10) will pull that versions most recent release.

**Comment by macmule** [comment]
Hi folks,

We had a need to hardcode the major version (as per the PR from @fuzzylogiq) & add the postinstall from @eholtham

As such, our recipes are at https://github.com/autopkg/dataJAR-recipes/tree/master/VMware%20Fusion%2010 & https://github.com/autopkg/dataJAR-recipes/tree/master/VMware%20Fusion%208

**Comment by justinrummel** [comment]
New py3 version now available.  This PR is so old I wouldn't want to include it now.  If this still needs to be fixed from the current version, please resubmit a PR and I'll quickly approve.

**Pull request closed without merging**
